# Generated by Django 2.2.2 on 2019-12-01 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20191201_1813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='privateevent',
            old_name='event_date',
            new_name='date',
        ),
    ]
